language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t saikumar/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true saikumar/docker-react npm run test
